# data=[
#     {
#         'idx':0,
#         'title':'ISTJ',
#         'summary':'The Inspector (Introverted, Sensing, Thinking, Judging)',
#         # 'content':'this is content1'
#         'para':'ISTJ represents one of the 16 personality types found on the Myers-Briggs Personality Indicator (MBTI).They gives great importance to tradition and old values. They are calm, quiet and practical. They are bright, logical and wise individuals. For them truth and facts are very important. Also, ISTJs are very loyal to their duties. All these attributes make them ideal employee and excellent analysts for any organization.',
#         'characteristics: ["They are physically and mentally well organized. This organization in their work helps them a lot to become more efficient than others.",
#         "Excellent planning skills and high intellectuality. They prefer to plan things in advance and to follow an orderly life. Whenever any interruption occurs in their plans, they try to come back on track as soon as possible. High intellectuality, reflect by well-organized, precise actions and decisions.",
#         "They are very calm and clear headed during tense situations. This calmness helps them to confront with stressful situations. They thoroughly analyses problems, then come to solution. Despite of any tense and overwhelm situation, their clear headed mind set show the right way to deal with problems.",
#         "Serious and committed in relationships. This commitment helps them to build strong and life-long relationships. Due to this reason, their chances to become a good life partner increases a lot. ",
#         "Believes in traditions and strives to follow them. They love to follow procedures, established rules and cultural values. ",
#         "They are well respected in the society. Their planned and organized work, calmness, dutifulness towards work and love for traditions make them well respected person in the society. ",
#         "Apart from all this, another unique key characteristic is they like to memorize details and facts. Often they go through details of various issues and these will make them good analysts.",
#         ],
#         'strengths':['Detail-oriented','Realistic',"Present-focused Observant ","Logical and practical" ,"Orderly and organized"],
#         'weaknesses':["Judgmental","Subjective","Tends to blame others","Insensitive"],
#         "well_known_examples":["Henry Ford","Queen Elizabeth II","George Washington"],
#         "relationships":{
#             "As_a_lover": "They are committed and loyal partners. They make tremendous efforts to make their relationships work. But, it is depend upon their priorities. When faced with criticism, they are likely to believe that their point of view is correct, as they have tremendous respect for facts. As their decisions are prone to thinking rather than feelings, it may be possibility that they will not very good to know their mates’ feelings. Best match is with ESFP or with ESTP.",
#             "As_a_parent": "They do best efforts towards raising their children with positive circumstance, care and security. ISTJ expects that their children honour their traditional family roles. As parents, they demand respect and authority from their children. They put their duties before their feelings. Also punishes if necessary. ",
#             "As_a_friend": "They are likely to spend time and get involve with people having similar interests as they have. Although they are kind of serious ones still they enjoy in activities and hobbies of their interests."

#         },
#         "Career_Opportunities":[
#             "Business Analyst","Accountant","Computer Programmer","Dentist ","Doctors","Lawyer","Military Leader"]
        
#     }
# ]
data=[
        {
            'idx':0,
            'title':'ISTJ',
            'summary':'The Inspector (Introverted, Sensing, Thinking, Judging)',
            'para':'ISTJ represents one of the 16 personality types found on the Myers-Briggs Personality Indicator (MBTI).They gives great importance to tradition and old values. They are calm, quiet and practical. They are bright, logical and wise individuals. For them truth and facts are very important. Also, ISTJs are very loyal to their duties. All these attributes make them ideal employee and excellent analysts for any organization.',
            'characteristics': ['They are physically and mentally well organized. This organization in their work helps them a lot to become more efficient than others.',
            'Excellent planning skills and high intellectuality. They prefer to plan things in advance and to follow an orderly life. Whenever any interruption occurs in their plans, they try to come back on track as soon as possible. High intellectuality, reflect by well-organized, precise actions and decisions.',
            'They are very calm and clear headed during tense situations. This calmness helps them to confront with stressful situations. They thoroughly analyses problems, then come to solution. Despite of any tense and overwhelm situation, their clear headed mind set show the right way to deal with problems.',
            'Serious and committed in relationships. This commitment helps them to build strong and life-long relationships. Due to this reason, their chances to become a good life partner increases a lot.',
            'Believes in traditions and strives to follow them. They love to follow procedures, established rules and cultural values.',
            'They are well respected in the society. Their planned and organized work, calmness, dutifulness towards work and love for traditions make them well respected person in the society.',
            'Apart from all this, another unique key characteristic is they like to memorize details and facts. Often they go through details of various issues and these will make them good analysts.',
            ],
            'strengths':['Detail-oriented','Realistic',"Present-focused Observant ","Logical and practical" ,"Orderly and organized"],
            'weaknesses':["Judgmental","Subjective","Tends to blame others","Insensitive"],
            'well_known_examples':["Henry Ford","Queen Elizabeth II","George Washington"],
            'relationships':{
                "As_a_lover": "They are committed and loyal partners. They make tremendous efforts to make their relationships work. But, it is depend upon their priorities. When faced with criticism, they are likely to believe that their point of view is correct, as they have tremendous respect for facts. As their decisions are prone to thinking rather than feelings, it may be possibility that they will not very good to know their mates’ feelings. Best match is with ESFP or with ESTP.",
                "As_a_parent": "They do best efforts towards raising their children with positive circumstance, care and security. ISTJ expects that their children honour their traditional family roles. As parents, they demand respect and authority from their children. They put their duties before their feelings. Also punishes if necessary. ",
                "As_a_friend": "They are likely to spend time and get involve with people having similar interests as they have. Although they are kind of serious ones still they enjoy in activities and hobbies of their interests."

            },
            'Career_Opportunities':[
                'Business Analyst','Accountant','Computer Programmer','Dentist','Doctors','Lawyer','Military Leader']
            
        },
        
        {
            'idx':1,
            'title':'ISTP',
            'summary':'The Crafter (Introverted, Sensing, Thinking, Perceiving)',
            'para': 'ISTPs passionate to understand the way things work. They are good at logical analysis, are action oriented and enjoy practical application. They prefer to perform practical actions rather than understand abstract ideas. Prefer to take things one day at a time, rather than make long term commitments. Their personalities are tough to determine than others. They enjoy having time to think alone. They seem to be unpredictable ones and deep down they are impulsive in nature.',
            'characteristics': ['They dare to differ. We can describe them as risk takers, who love variety of new experiences. They often engage in risky hobbies.',
            'They are highly practical, realistic and result oriented. Whenever they confront with some problem, they quickly try to understand the cause and find solution on it. As there action oriented attitude shows, they want to explore new things and try to find solutions by trial and error. Often solutions may not find, still they give their best try by performing them.',
            'They try to solve problem on their own. They are determined to their work and try to finish it on their own. They enjoy to do work alone or in small groups. They prefer to do most of their work independently and can maintain focus on the task at hand.',
            'Constantly gathers facts about the environment and stores them away for letter. Their exploratory nature help them to gather new facts and information which they can use later to find quick solutions.',
            'They focus on living in the present, rather than in the future. Their curious, problem solving, logical and reflective nature help them to engage with things rather than just imagine and observing.',
            'They are excellent trouble shooters who are easily able to find solutions to practical problems they confront. Problem solving attitude makes them much efficient.',
            'They are often described as quiet, but with an easy going attitude with people.',
            ],
            'strengths':['Logical','Learns by experience','Action-oriented','Realistic and practical','Enjoys new things','Self-confident and easy going','Flexible','Problem solver'],
            'weaknesses':['Difficult to get to know','Insensitive','Get bored easily','Risk-taker','Does not like commitment'],
            'well_known_examples':['Michael Jordan','Bear Grylls','Scarlet Johnson'],
            'relationships':{
            'As_a_lover':'They are very intense, exciting and attractive individuals. They need their own space in a relationship. If a relationship becomes boring or oppressive to ISTPs they will either fix it or move on. They do not like to make lifelong commitments. They like to listen to other people’s views, but are generally non-commit about experiencing their own opinions. Does not have a well-developed feeing side. Best match is with ESTJ or with ENTJ.',
            'As_a_parent':'They are flexible and also gives a lot of space to their children. They do not likely to be directed and controlled by others. Similarly, they do not put tremendous pressure on their children to direct and control them. ISTPs will enjoy spending time with their children in outdoor activities too.',
            'As_a_friend':'Hobbies and interests are the main basis of a friendship. They generally have no interest with people who spend very less time with them and with people have no common interests. They also have a strong need to be alone.',
            },
            'Career_Opportunities':['Engineer','Technician','Carpentry','Scientist','Forensic Science','Mechanic'],
            },

        {
            'idx':2,
            'title':'ISFJ',
            'summary':'The Protector (Introverted, Sensing, Feeling, Judging)',
            'para': 'ISFJs are practical, compassionate, gentle and caring. They strive for and to protect others. They are most warm and kind-hearted people. They are philanthropists. They take personal interest in responsibility for their work, goals and obligations. They are dedicated to maintain harmony with others and are loyal to established methods and values. They also enjoy mentoring others.',
            'characteristics': ['They have powerful emotions and they are highly aware of peoples’ feelings. They are extremely aware of their own internal feelings as well as feelings of others. People often share their problems with them and feel pretty good after talking with them.',
            'They are very stable, practical and down-to-earth persons. They are caring and warm. Everyone find it very easy to make bond with them. They are cautious towards thoughts of others.',
            'They are hard workers and often they try to achieve a point of perfectionism. They take extreme interest in responsibility for their work, goals and obligations, consistently going above and beyond, doing everything that they can to not just meet but exceed all expectations.',
            'They are true philanthropists. They are always ready to give back and return generosity, with even more generosity. Things and people in which they believe, they support them with unselfishness and enthusiasm. They are kind and considerate & highly aware of people’s feelings.',
            'They are extremely uncomfortable with conflicts and confrontations. They always try to avoid such situations. They are peace loving people, who always try to maintain and establish harmony.',
            'ISFJs respect a lot towards traditions and laws. They believe that such a system will definitely work well. They prefer highly structured and consistent environment, where they are given step-by-step instructions.',
            'Often they hide their own feelings and do not like to express their feelings with others.',
            ],
            'strengths':['Reliable and patient','Practical','Supportive','Imaginative and observant','Loyal and hard working','Good practical skills','Sensitive','Eye for detail'],
            'weaknesses':['Dislikes abstract concepts','Repress Their feelings','Overload themselves','Avoids confrontation','Dislikes change','Neglects own needs'],
            'well_known_examples':['Mother Teresa','Naomi Watts','Tiger Woods'],
            'relationships':{
            'As_a_lover':'They gives great importance to their personal relationships. They take their commitments very seriously and always try to find & maintain lifelong relationships. Instead of being intense feeling for their partners, they hide lot of things until they find reason to express them. If their relationships are getting over, they tend to take blame on their own shoulders. Best match is with ESTP or with ESFP.',
            'As_a_parent':'They try to teach their children rules and observations of our society so that they can make their children as responsible and independent adults. But, ISFJs feel some difficulty during punishment and discipline. Also, they set out boundaries for their children. Due to this values and traditions oriented nurturing, they seem to be an ideal parents.',
            'As_a_friend':'They enjoy to spend time with their friends and colleagues. Often they share problems with them and ask for opinions to deal with various circumstances. As ISFJs are being caring, understanding, ward-hearted ones they can easily become trustworthy friends. They love to spend their time with diverse types of people.',
            },
            'Career_Opportunities':['Social worker','Teacher','Administrator','Health care worker','Human resource professional','Counsellor','Office manager'],
            },

        {
            'idx':3,
            'title':'ISFP',
            'summary':'The Artist (Introverted, Sensing, Feeling, Perceiving)',
            'para': 'ISFPs are active, goal driven and creative. They make others feel better with their warm and enthusiastic nature. They creates a sense of spontaneity, they are adventures and seem unpredictable ones. They live in the present, hard to get to know. They always try to push hard towards their passion. ISFPs often considered as naturally born artists and also trend setters. They love to explore new things.',
            'characteristics': ['They are not kind of person, who simply accepts abstract ideas and theories. Rather, they would like to work on facts and details through performing them. They prefer to do works, rather than only dreaming about them. They believe to learn new things by performing tasks and tend to avoid tedious abstract type of learning.',
            'They follow their passions and they are kind of explorative in nature. Due to these reasons, they do not like be bind by boundaries and restrictions.',
            'They love adventures. They always try to reinvent and do experiments with their own lives and with new perspectives. ISFPs participates in many risk taking sports, it is very common and attractive to them.',
            'ISFPs generally seen as the most spontaneous and unpredictable ones amongst all introverts. They love to explore new ideas and activities. They like to experiment and come up with ideas that no one thought of before. They are kind of inventor ones.',
            'They are not routine followers. Often we follows ideal personalities, most probably they are good planners, schedule followers. But, ISFPs are not too good to plan things. Instead of this, they would like to go with unplanned things. Routines feel boring to them.',
            'One remarkable unique feature belongs to them. They are kind of adventurous and unrestricted ones, but they take life very seriously. They have strong set of values. They live life in accordance of what they feel good and rebel against anything which conflicts with their goal.',
            'People with ISFP personality are warm and sympathetic. They genuinely care about people and like to show their love through actions rather than words. They are warm, friendly and affirming by nature.',
            ],
            'strengths':['Flexible and cooperative','Practical','Enjoys hands-on learning','Energetic','Curious and creative','Passionate','Sensitive to others','Artistic'],
            'weaknesses':['Dislikes abstract, theoretical information','Reserved and quiet','Over competitive','Easily stressed','Strong need for personal space','Dislikes arguments and conflict'],
            'well_known_examples':['David Beckham','Lady Gaga','Michael Jackson'],
            'relationships':{
            'As_a_lover':'They are warm and giving people. They may appear to be light-hearted, in fact they take relationships extremely seriously. They are seeking for lifelong relationships and committed to their partners. Being an introvert, they may be lack in healthy conversations. Best match for this kind of person is extraverted one. They find very difficult to deal with arguments and conflicts. Best match is with ESFJ or with ENFJ.',
            'As_a_parent':'Does not have lot of expectations from their children. They love to play games and spend time with their children. Their gentle manner and kind heart to raise their children sometimes cause lack of structure and discipline. They also like to do special things for them, for instance – give surprise on special days and plan an outdoor activity.',
            'As_a_friend':'They spend time with friends, who share their interests with ISFPs and understand & accept ISFPs. Do not have much patience or tolerance for people who try to judge them. Often ISFPs considered as quiet and reserved one, but they opened up only with those, who know them very well.',
            },
            'Career_Opportunities':['Chef','Artist','Composer or Musician','Nurse','Psychologist','Teacher','Designers'],
            },
            
            {
            'idx':4,
            'title':'INFJ',
            'summary':'The Advocate (Introverted, Intuitive, Feeling, Judging)',
            'para': 'INFJs are visionaries and idealists. They never accept anything on surface level.They are gentle, caring, complex and highly intuitive individuals. They live in a world of hidden meanings and possibilities. An INFJ has an uncanny insight into people and situations. They enjoy thinking about deep topics and contemplating the meaning of life. INFJs are capable of taking their values and using them to bring about positive and lasting change.',
            'characteristics': ['INFJs often considered as firm and kind of stubborn people. They find hard to accept other person’s belief, as they have already pre-set values with them. They never take step back on whatever they have said. Whenever their views and beliefs are challenged, they will do debates and arguments if necessary.',
            'Warm, caring and friendly nature helps them to understand other people’s feelings. They often work for well-being of others without asking for any return. Due to these, they find very easy to build new and strong relationships.',
            'They are very sensitive and cautious towards all people. People feel secure to share their problems with them. This sensitive nature helps INFJs to understand problems of other people. They are careful not to hurt anyone by their words and actions. They are very good at reading people’s mind and can easily sense what particular person is feeling.',
            'They are planner and strategists. At work, their creativity makes them special amongst others. They respect rules and deadlines. Prefer to do things systematically. Because of their perceptive nature, they are good at remembering details which help them to build efficient plans.',
            'They are mysterious and secretive. They rarely share their feelings with other people. They can be difficult to understand for other people. They stay away from social events, where they have to mingle with others. Prefer to be secretive, INFJs take much time to trust on others and rarely, they reveal private information with people.',
            'INFJs learn best in a highly structured and consistent environment, where they are given step-by-step instructions and clear expectations.',
            'They are protective of tradition and not quick to adapt changes.',
            ],
            'strengths':['Passionate','Principled','Quiet and reserved','Creative and artistic','Insightful','Organized and structured','Idealistic','Values close and deep relationships'],
            'weaknesses':['Over sensitive','Perfectionist very high expectations','Sensitive to criticism','Intensely private','Stubborn','Dislikes confrontation'],
            'well_known_examples':['M K Gandhi','Plato','Leo Tolstoy'],
            'relationships':{
            'As_a_lover':'INFJs constantly try to build a perfect relationship. They always look for depth and meaning in their relationships. Often they take a long time to choose their partner, as they always strive to get perfect one. They are excellent listeners and pretty good at interactions, this will help them to build strong emotional bond with their partners. Best match is with ENTP or with ENFP.',
            'As_a_parent':'As they are so skilled to understand the feelings of people. They are strongly connected with their children. INFJ parents have much high expectations and also sometimes they want so their own beliefs and values in their children. They are very warm and caring parents. They raise their children with love and care.',
            'As_a_friend':'They like to spend time with those who give importance to their values and beliefs. They are looking for friends, who always help them to grow and improve.',
            },
            'Career_Opportunities':['Counsellors','Psychologists','Religious teachers','Artist or Musician','Entrepreneur','Health care sector','Social or Environmental scientist'],
            },
            
            {
            'idx':5,
            'title':'INFP',
            'summary':'The Mediator (Introverted, Intuitive, Feeling, Perceiving)',
            'para': 'They are driven by high values. Often INFPs considered as “idealist” or “mediator”. They spend a lot of time to explore their own purpose in life and always think how they can help them to make world a better place. They have their own core values. They are compassionate and caring. They are also known as “Healers” due to their sympathetic nature.',
            'characteristics': ['They are idealists and perfectionists who drive themselves to achieve their goals in life. They always try to find meaning of life and how they serve humanity. They always explore ideas that will help them to accomplish these goals.',
            'INFPs are good mediators and they try to avoid conflicts. Even in conflict situations, they strive to understand both sides of an argument, no matter who is right and who is wrong. Their thoughtful nature helps them to analyse both sides of any conflict and to solve any issue intellectually rather than emotionally.',
            'They tend to be introvert, quiet and reserved. They gain energy by staying alone.',
            'INFPs have their own set of standards and principles from which they base their actions and decisions. They have strong personal value systems. Their words and actions tell the story of this. They like to follow this set of principles throughout their life.',
            'While others would make decisions based on their past experiences, INFPs rely more heavily on their intuition and gut feelings. They look beyond experience to search for an underlying meaning. They find signs and patterns in everyday circumstances and consider metaphors and symbols that they see around them when making decisions.',
            'They often delay their important decisions just in case something about the situation changes. Their decision making process is based on personal values rather than logic. Sometimes, this will result in disagreements and conflicts with others.',
            'They are introverts. But, still they love to be around people and spend time with them. They are naturally warm and compassionate. Also, they are good listeners.',
            ],
            'strengths':['Idealism','Dedication','Loyal and committed','Supportive and encouraging','Flexible and diverse','Caring and sensitive','Values close relationships','Good at seeing "the big picture" '],
            'weaknesses':['Over idealistic','Impractical','Extreme dislike of conflict and criticism','May react emotionally in stressful situations','Tendency to blame themselves for problems','Unfocused','Overlooks details'],
            'well_known_examples':['William Shakespeare','Bill Watterson','Chris Martin'],
            'relationships':{
            'As_a_lover':'They are dreamers and idealistic. They believe in power of true love and try to find soul mate. They are devoted and loyal. INFJs accept their partners as they are and give value to their independence. They help their partners to help, grow and pursue their goals. They take their relationships very seriously. Best match is with ENFJ or with ESFJ.',
            'As_a_parent':'INFJs are warm, caring and open minded parents. They give freedom to their children to make their opinions, to discover things and to grow in unique way. They also try to pass their values. As a parent, they take their role much seriously and always try to support and protect their children.',
            'As_a_friend':'They prefer and trust small, intimate circle of friends. They are looking for lasting and authentic friendships with people who share their desire to think and feel deeply. They respect wide views of all sorts of people, this will make them ideal friend for others. But, they are kind of picky person in case of lifelong friendships.',
            },
            'Career_Opportunities':['Writer','Counsellor','Human resource specialist','Psychologist','Social worker','Teacher','Therapist'],
            },
            
            {
            'idx':6,
            'title':'INTJ',
            'summary':'The Architect (Introverted, Intuitive, Thinking, Judging)',
            'para': 'INTJs considered as highly creative, analytical and logical. They are true introverts; they tend to spend time in their own company. They prefer to work alone and try to remain self-sufficient; they are more interested in big ideas and theories. They always try to find why the way things are happen. They are deliberate and long range thinkers. They live in a world of ideas, analysis and strategy. They love new ideas and seek to improve world around them.',
            'characteristics': ['They enjoy logical reasoning and complex problem solving. They approach life by analysing what they see around them and always try to find causes of things. They are eager to improve systems with their innovative ideas. The complex problem solving approach help them a lot to innovate and explore new things.',
            'INTJs are ambitious, self-confident, deliberate and thinkers. Due to this, they tend to move towards science and engineering applications or business applications which involved proper strategy and planning. They are always committed to finding best strategies to their goals.',
            'Due to their true introvert nature, they seem to be detached from the society. But, this is not the case, because they values true friendship and relations too.Their logical, analytical skills always engage them to find new ideas and possibilities. Their dedication to works makes them introverts.',
            'They are extremely logical and values knowledge & efficiency in their life. They always try to improve their surroundings. Their approach is to gain knowledge and to implement it, so that they can build efficient systems.',
            'INTJs would question and challenge existing procedures. This makes them efficient and impartial decision makers.',
            'They are brutally honest, direct and rational. They will say what they really think and give solutions that they believe are right. They rely on their head rather than heart. This will help them to see the world impartially. Sometimes, people can considered them as insensitive ones, but in reality they are rational ones.',
            'They can easily get bored by following mundane routines. Rather they like to spend as much time as can in things they love to explore and innovate.',
            ],
            'strengths':['Enjoys theoretical and abstract concepts','Strategy','Extremely intelligent and capable','Good listeners','Self-confident','Not threatened by conflicts or criticisms','Determination','Innovative'],
            'weaknesses':['Perfectionism','Imbalance','Judgemental and intolerant with less capable','Arrogant','Over critical','Dislikes talking about emotions','Sometimes seems callous or insensitive'],
            'well_known_examples':['Vladimir Lenin','Isaac Newton','Martin Luther'],
            'relationships':{
            'As_a_lover':'As they are more concerned with the facts rather than protecting people’s feelings, they may seem as insensitive. They find it very difficult to handle relationships, especially in an early stage. They are able to get on track easily as compare to other personalities after the relationship get broken. Best match is with ENFP or with ENTP.',
            'As_a_parent':'Try to grow their children by giving lot of space. Their children should be intelligent, autonomous and independent is the primary goal of their parental life. They may lag to provide emotional support to children. They have high expectations from their children and raise them in a way that they can solve their problems by their own.',
            'As_a_friend':'INTJs tend to prefer friends who are introverted, rational and low on emotional drama. Establishing and maintaining relationships take much time and in the case of INTJ, they are spending their much time about future and possibilities. It becomes difficult for them to make friends.',
            },
            'Career_Opportunities':['Engineer','Scientist','Economist','Mathematician','Computer programmer','Judge','Lawyer','Doctor','Teacher'],
            },
            
            {
            'idx':7,
            'title':'INTP',
            'summary':'The Thinker (Introverted, Intuitive, Thinking, Perceiving)',
            'para': 'INTPs live rich worlds inside their minds, which are full of imagination and excitement. They are fascinated by logical analysis, systems and designs. They are preoccupied with theory, and search for the universal law behind everything they see. They want to understand the unifying themes of life, in all their complexity. They spend much of their time in their own heads: exploring concepts, making connections, and seeking understanding of how things work.',
            'characteristics': ['They are very tolerant until their core beliefs or values are not being violated. They may take a very different stance on violation of core belief. They do not like to lead or control people. They seem very shy when they are meeting with new people. But, once INTPs became familiar with them they become strongly confident.',
            'They approach problems with enthusiasm. They love new ideas and become very excited over abstractions and theories. In the way of defining their own approach, they may often ignore existing opinions. They have unique perspectives and they are vigorous intellect.',
            'INTPs are typically non-traditional. They love to follow their own unique way to look at the things, rather than to follow the crowd. They prefer to think “out of the box”. They are not like to place much emphasis on traditional goals such as popularity and security. They analyse ideas in new ways.',
            'They live within their own head. They have strong ability to analyse problems, identify patterns and come up with logical explanations. Often they not give much importance to the external world. Their mind is most active place. They love to talk about science, mathematics, computers and large theoretical problems of the universe.',
            'They are not pretty good at knowing and understanding others. Often they may seem to be insensitive. As they live in their own world, rarely they focus on details on what is happening outside their world.',
            'They are usually very independent, unconventional and original. They love do tasks in their own style. They use their logical and analytical skills to bring out solutions. They are not like to involve too much with people. But, in case they involve they remains original and impartial.',
            'Their decision making is totally based on logical facts and objective information and not on subjective feeling.',
            ],
            'strengths':['Logical and objective','Analytical brilliance','Abstract thinker','Independent','Loyal and affectionate with loved ones','Imaginative','Open minded','Curious'],
            'weaknesses':['Difficult to get to know','Insensitive','Uncertain','Not usually good at practical matters','Struggles to follow rules','Has trouble expressing feelings','Perfectionistic'],
            'well_known_examples':['Albert Einstein','Charles Darwin','Socrates'],
            'relationships':{
            'As_a_lover':'They are faithful and loyal partner. They take their commitments quite seriously. They are not over demanding. They are honest lovers. But, INTPs face problems while understanding feelings of their partner and also to express their own feelings. They do not like to deal with messy complications and conflicts. Best match is with ENTJ or with ESTJ.',
            'As_a_parent':'They like pass their knowledge on kids. They give space to their children to grow as independent and as rational adult. They are very caring and supportive, but they can lag in understanding emotional needs of their children. INTP want to empower their children to solve their own problems and meet their own needs.',
            'As_a_friend':'Their friendships are knowledge-based, where they like exchange ideas, concepts and theories. They are very slow to form friendships.',
            },
            'Career_Opportunities':['Computer Programmer','Software Developer','Engineer','Mathematician','Scientist','Lawyer','Accountant','Writer or Author','Chemist'],
            },
            
            {
            'idx':8,
            'title':'ESTP',
            'summary':'The Persuader (Extraverted, Sensing, Thinking, Perceiving)',
            'para': 'ESTPs are outgoing, action-oriented and dramatic. They are more likely to focus on details than taking a broader view of things. They are logical. ESTPs also considered as one of the most common personality type. They are enthusiastic, excitable and living in the world of actions. They live in the present and give little importance to theory. They love to have fun.',
            'characteristics': ['They make decisions quickly. When confront with any problem, this type of persons look at the facts and devise the solutions. They do not like to get stuck on things. Rather than planning and executing the task, they prefer to execute actions as early as possible by quick decision.',
            'They are adventurous kind of person. They love to take risks in life. They like to play sports which involve adventures; they are always seeking for new experiences. These are people who want to be on the go, doing, seeing, and experiencing things. They prefer to be in the field rather than stuck behind a desk.',
            'They live in the present moment and like to see immediate results. ESTPs always try to live every moment of life. They are not planners and strategists. They do not like plan things in advance. They focus on present and deeply engage in activities they like to do so.',
            'They love to have fun and become centre of attention. In any place, we can easily spot ESTPs. They are spirited, spontaneous and fun-loving. They are amongst the active members of the group. They’re often chatting, joking, and flirting with friends and strangers alike. They enjoy engaging playfully with others and amusing everyone around them with their irreverent sense of humour.',
            'They have strong social skills. They are very observant. Often they notice things or details, that other will never notice. They are always looking for some action or activity. Sometimes, they considered as “fast-talkers” as they are always few steps ahead than others.',
            'They are highly unpredictable ones. They are always in search of joy and fun. They do not like any ties or boundaries. Quick decision making and action oriented nature results in their unpredictability.',
            'ESTPs are full of passion. They will try to break traditional boundaries, if there are obstacles in their path. They love to do things that make them enthusiastic.',
            ],
            'strengths':['Gregarious, funny, energetic, charming','Clear headed dealing in emergency situations','Rational and practical','Influential and persuasive','Action-oriented','Can-do attitude','Observant','Sociable'],
            'weaknesses':['Impatient','Unstructured','Not good long-range planner','Competitive','Dramatic at times','Easily get bored','Insensitive'],
            'well_known_examples':['George Bush','Donald Trump','Winston Churchill'],
            'relationships':{
            'As_a_lover':'They are very sensual and earthy. They bring lot of fun and energy in their personal relationships. Commitment is not a strong point in the lives of ESTPs until they reach the point to settle down. They may lack in areas of giving gratitude and support to their partners. Best match is with ISFJ or with ISTJ.',
            'As_a_parent':'They allow their children to have their own choices. They are like to spend time with their children and do fun. They are not too disciplined towards their children. They give sufficient freedom to their children and also encourage them to follow their hearts. They may not have much interest in emotional discussions.',
            'As_a_friend':'As they are fun-loving, adventurous and charming people, it is very easy to approach ESTPs and mix with them. They observant people, as a result they know how to act appropriately with everyone. As they are fast-paced and quick moving persons, so there is high tendency that they do not form lifelong friendships.',
            },
            'Career_Opportunities':['Entrepreneur','Marketer','Police officer','Military officer','Detectives','Sales Manager'],
            },
            
            {
            'idx':9,
            'title':'ESTJ',
            'summary':'The Director (Extraverted, Sensing, Thinking, Judging)',
            'para': 'ESTJs are hardworking traditionalists, eager to take charge in organizing projects and people. They tend to go in a systematic and methodological way.They are more likely to focus on current objectives rather than long-term goals. They look for rules to follow and standards to meet and often take leadership roles. They have strong beliefs and committed to traditions & laws.',
            'characteristics': ['ESTJs are natural born leader. They like to take initiatives. They like to take leadership roles and supervise the working of organization. They make sure that things are going smoothly or not. They emphasise on laws and traditions. As a result, they may sometimes seem to be rigorous. As a leader, they love to take charges and see challenges as opportunities.',
            'People often approach them as a guide or counsellor and ESTJs are always ready to help them or give any kind of assistance. They make difficult tasks easy for people, by providing them proper guidance and direction.',
            'They are hardworking, organized and dedicated characters. They prefer to do things in a systematic way, so that they can complete any task with given standards and in an efficient way. Organization of things helps them to finish the task before the deadlines.',
            'They are planners or we can say them as strategists. They like to make plans before taking actions. Planning is very crucial to them to accomplish their goals.As a result, they seem to prepare to face things. They like to keep an eye on checklists and schedules. They often have many strategies to confront with the problems.',
            'They are ethical. They respect traditions, principles and laws a lot. They expect people should follow principles and laws as he/she is doing.',
            'Often ESTJs face difficulties, when they face new things, which are unconventional to them. As an ethical and traditional person, sometimes they seem to be unfamiliar with new ideas. Frequently, they seem to not willing to accept new values and often disagree with them.',
            'They like to be around people. They are active with high energy and zeal. They love to bring everyone together. Their enthusiasm and talkative nature often attract other people.',
            ],
            'strengths':['Practical and realistic','Enthusiastic','Patient and reliable','Self-confident','Hard-working','Organization','Strong leadership skills'],
            'weaknesses':['Insensitive','Inflexible','Judgemental','Uncomfortable with unconventional situations','Difficulty in expressing feelings','Argumentative','Stubborn'],
            'well_known_examples':['Kamala Harris','Michelle Obama','Emma Watson'],
            'relationships':{
            'As_a_lover':'They seek stability and security in their lives, and once they have made a commitment it will be lifelong and unalterable. They are guardians and protectors by nature. They face problem, while understanding mate’s feelings. Often they face difficulty to express their own feelings. But, they are honest and committed partners. Best match is with ISTP or with INTP.',
            'As_a_parent':'ESTJs take their duties and obligations quite seriously. They do not have much tolerance for inefficiency, messiness and frequent mistakes done by their children. For their children, ESTJ parents seem to be strict and traditionalist ones. Their ultimate goal is to raise their children to be hard-working and productive.',
            'As_a_friend':'As they are sociable, ESTJs love to spend time with their friends. They like to go in social activities and events to enjoy with their loved ones. They like to spend free time with their friends pursuing some activity or hobby. They are loyal friends. They are strong, traditional friends who appreciate loyalty and shared values.',
            },
            'Career_Opportunities':['Politician','Teacher','Judge','Manager','Police officer','Physician','Administration'],
            },
            
            {
            'idx':10,
            'title':'ESFP',
            'summary':'The Performer (Extraverted, Sensing, Feeling, Perceiving)',
            'para': 'ESFPs are often described as entertainers or “class clowns”. They love being the centre of attention. They have strong interpersonal skills and they love people & new experiences. They are thoughtful explorers, who enjoy learning.They are spontaneous, fun-loving, energetic and pleasure seeking personalities. These individuals go with flow of things.',
            'characteristics': ['They live in the moment and enjoy what life offers. They like keep busy, feeling their lives with hobbies, sports, activities and friends. They love to seek fun. They prefer to do things that will make them happy and joyful. They love excitement. Rather than concern about tomorrow, they live the present moment.',
            'They love excitement and drama. They have special talent of entertaining people. This is the reason, why they become centre of attention. People love to spend time with them. Due to their strong interpersonal skills, it is very easy for them to make new friendly connections.',
            'They are warm, generous, sympathetic and concerned for others. They like to be around people. Often people share their problems with them due to their generous and sympathetic nature. ESFPs have very down-to-earth approach to friendship and love. People often feel joyful, when ESFPs share their experiences to make feel better them.',
            'They tend to be very practical and resourceful. They prefer to learn through practical experiences and dislike book learning or theoretical, abstract discussions. ESFP students often lag in traditional classroom learning, but they are much better in learning through direct experience.',
            'ESFPs pleasure-seeking nature often takes them away from their duties and responsibilities. They do not like to become an ethical, disciplined and responsible person.',
            'They prefer to be simple, straight-forward and honest. Although they are warm and sympathetic, they prefer to remain in light and happy relationships.They do not like complexities in their life.',
            'They are very good at observing the environment and aware about environment. They are cautious about details, and it helps them in social interactions.',
            ],
            'strengths':['Optimistic and gregarious','Aesthetic','Observant','Positivity','Creative','Enjoys people and socializing','Focused on the present','Bold and Practical'],
            'weaknesses':['Dislikes abstract theories','Becomes bored easily','Poor planning','Sensitive to criticism','In conflict situations','Unfocused'],
            'well_known_examples':['Will Smith','Serena Williams','Bill Clinton'],
            'relationships':{
            'As_a_lover':'They do not like commitments and securities, so it may be a big problem for ESFPs.  They like to enjoy every moment of their life. Often, they see commitment, responsibilities and long-term plans as their binding boundaries. Also, they are not god at handling conflicts. Best match is with ISTJ or with ISFJ.',
            'As_a_parent':'They prefer to give fun-loving environment to their children and not strict, disciplined one. They constantly devise new and exciting ways to enjoy their time with their children. They face difficulty while punishing them or to raise in strict disciplined environment.',
            'As_a_friend':'They are very popular amongst their friends. They enjoy every day like a party or celebration. ESFPs mixed with diverse section of friends, but they prefer to spend time with those having fun-oriented lifestyle. They always seek to explore new places and meet with new people.',
            },
            'Career_Opportunities':['Artist','Actor','Musician','Social worker','Psychologist','Coach','Photographer','Fashion designer'],
            },
            
            {
            'idx':11,
            'title':'ESFJ',
            'summary':'The Caregiver (Extraverted, Sensing, Feeling, Judging)',
            'para': 'ESFJ has a strong value system, they have their own ideas of how things should be and will typically share those opinions freely. ESFJs typically form their values and morals based on the world around them, rather than what guides them on an internal basis. They respect authority and follow the rules. ESFJs value loyalty and tradition, and usually make their family and friends their top priority. They are sensitive to the needs of others and often dedicated to responsibilities.',
            'characteristics': ['They enjoy helping others. They are always ready to listen with warmth and genuine sensitivity. They are sensitive, helpful and sociable. They are ready to serve others. They try to solve problems of other people full-heartedly.',
            'As they are very sensitive and caring people. ESFJs easily get hurt by misbehaviour of other people. It is also possibility that they may fall into the trap of bad people. People can use them when needed and can hurt them after work done.',
            'People often see them as a role model. Their love for people and socialization naturally places ESFJs in positions of power. Their sensitive, energetic, compassionate and sociable nature makes them popular and well-liked amongst all.',
            'Physical appearance, social status, hierarchy and traditions are very high priorities in their life. They like to be good looking person and try to achieve and maintain respected position in society. Besides that they have high respect for hierarchy and traditions.',
            'Their decision making is based on what they feel i.e. by heart and not by brain. Hence, they are likely to get hurt by criticisms, conflicts or arguments. They feel motivated and full of energy & enthusiasm, when someone appreciates their work. Emotions play a vital role in their lives.',
            'They are extremely organized. They prefer to have future plans and act accordingly to their plans & schedules. They like to go with systematic manner, have disciplined in their work and life. They face difficulties while there is any uncertainty.',
            'They prefer to live in the real world rather than the world of imagination. They like to mix with people. They are active and enthusiastic. They are good observant and are well aware of facts and details of surrounding.',
            ],
            'strengths':['Kind and loyal','Strong practical skills','Confident','Generous','Organized','Good at connecting with others','Enjoy helping others','Strong sense of duty'],
            'weaknesses':['Needy','Vulnerable to criticism','Too selfless','Inflexible','Sensitive to criticism','Dislike change','Worried about social status'],
            'well_known_examples':['Ed Sheeran','Selena Gomez','Vin Diesel'],
            'relationships':{
            'As_a_lover':'ESFJs are very caring people. They give lot of care and attention to their partners. They take their commitments seriously. Conflict or criticism is like a pitfall for them. There is big role of appreciation and support in a relationship. They like an organized life. They prefer stable, harmonious relationships. Best match is with ISFP or with INFP.',
            'As_a_parent':'They are extremely committed to their roles and duties. They will create structured environment for their children, where their boundaries are well-defined. These strict and disciplined environments sometimes become the cause of conflict. ESFJs want their children to adopt and follow their own strong system of values.',
            'As_a_friend':'They are very loyal friends. Sometimes, they consider friendship as another task of responsibility. They are valued by others for their warmth and kind-heartedness. They have a special skill at seeing best in others. They usually have a very large number of close friends. They often like to spend time with friends who value them and appreciate them.',
            },
            'Career_Opportunities':['Teacher','Nurse','Physician','Social worker','Counsellor','Child care','Therapist'],
            },
            
            {
            'idx':12,
            'title':'ENFP',
            'summary':'The Champion (Extraverted, Intuitive, Feeling, Perceiving)',
            'para': 'They often describe as very charming, enthusiastic, energetic, creative and independent. They are highly individualistic. They strive to create their own methods, habits, ideas and actions. Most of the time, ENFPs operate from their feelings. But, they are highly perceptive and thoughtful. They are very bright and full of potential. Generally, achieve good degree of success in their area of interest.',
            'characteristics': ['They do not like to perform boring, mundane or routine tasks. They are not naturally good at following things through to completion. They avoid tasks that are detail and routine-oriented. They do not like tasks which can make them feel as confined.',
            'Generally, they do not like to being controlled by someone or to go in a single direction only. They have multiple interests and also they are good at many things, hence they always want to explore new ways and ideas. They do not like to follow rules and become a follower of someone.',
            'They are passionate and enthusiastic people who are full of potential. They live in the world of possibilities and excited about new things. They have broad range of skills and talents. They are good at most of the things in which they are interested. They may go through several different careers in their lifetime.',
            'They are motivating persons. They always seem to be full of zeal and energy. They can become a good leader, because of their broad skill set, creative and flexible nature, adaptability and compassion toward people.',
            'Imaginative and original, ENFPs often have a strong artistic side. They are drawn to art because of its ability to express inventive ideas and create a deeper understanding of human experience.',
            'They enjoy being around people. They prefer to avoid arguments and conflicts. They are warm and genuinely interested in people. They have excellent inter-personal skills. They are highly perceptive, when understanding how individuals and group function. They are often friendly and outspoken.',
            'They can become easily distracted, especially when they are working on things that seem them as boring or as uninspiring.',
            ],
            'strengths':['Warm and enthusiastic','Curious','Excellent communicators','Empathetic and caring','Strong social conscience','Motivational, inspirational','Funny and spontaneous','Highly creative'],
            'weaknesses':['Poor practical skills','Highly emotional','Disorganized','Get stressed easily','Dislike conflict and criticism','Overthinking','Struggles to follow rules'],
            'well_known_examples':['Walt Disney','Justin Bieber','Taylor Swift'],
            'relationships':{
            'As_a_lover':'They make warm and passionate partners who are generally eager, willing and able to do whatever it takes to make the relationship a positive place. They take their commitments very seriously and they are deeply loyal & faithful. If they have to leave their relationship or it breaks due to any reason, then they take failure as their own fault. Best match is with INTJ or with INFJ.',
            'As_a_parent':'They strive consistently to create a positive, ideal environment for their children’s growth. They are very playful. They give their children lot of support and space. Often they try to pass their strong beliefs and principles to add discipline in children’s lives.',
            'As_a_friend':'They are warm and sociable people. They help their friends to improve themselves and try to lift them up.  They like to see best in others and are likely to bring out best in others. They mixed with all sorts of people. They are open-minded. They get irritated and emotional when the judger expresses negative opinion about them.',
            },
            'Career_Opportunities':['Actor','Journalist','Musician','Editor','Nurse','Social worker','Counsellor','Psychologist'],
            },
            
            {
            'idx':13,
            'title':'ENFJ',
            'summary':'The Giver (Extraverted, Intuitive, Feeling, Judging)',
            'para': 'ENFJs are warm, loyal and sensitive. They are capable of forming friendships with all personality types, even with introverts. They have ability to influence and even manipulate others. They are highly ethical and principled. They spend their most part of their life in imagination rather than in the real world. Rather than focusing on “now”, Often they are sink in thoughts of possibilities of future.',
            'characteristics': ['ENFJs are people-focused individuals. They are extroverted, idealistic, charismatic, outspoken and highly ethical and usually know how to connect with other people no matter whatever their background is or whatever their personality is.',
            'They are loyal, reliable, warm, caring and influential. Due to these characteristics they easily form strong bonds with all sorts of people. Due to their kind nature, they often become the centre of attraction to the people. People love to spend time with them.',
            'They are always strives to maintain balance between their extraverted and intuitive character. When they spend too much time alone, they feel depressed. And when they spend too much time with others, he tends to feel overwhelmed and unable to process everything that has been on his mind.',
            'They are extremely organized. They like to work systematically. They prefer to go with plans and strategies. They may face difficulties while dealing with uncertainties.',
            'Their decision making is primarily based on heart and not on brain. They mainly rely on intuition and feelings. They tend to live in imagination rather than in reality.',
            'For an ENFJ, having an ideal to fight for is the true meaning of life. They believe that find their purpose and ultimate goal is more important than material possession. They believe that there is something charismatic in this world and hence they always strive to find things that will give some meaningful aim to their life.',
            'ENFJs have great people skills and are often described as warm and supportive. They are great at encouraging other people and derive personal satisfaction from helping others. ENFJs are often so interested in devoting their time to others that they can neglect their own needs. They are good at bringing consensus among diverse people. They can be outstanding leaders, and also become influential and motivational.',
            ],
            'strengths':['Outgoing and warm-hearted','Reliable','Charismatic','Leadership skills','Wide social circle','Encouraging','Organized','Peacekeeping'],
            'weaknesses':['Struggle to make tough decisions','Overly sensitive','Overly Idealistic','Too selfless','Rigid and uncompromising','Overprotective','Manipulative'],
            'well_known_examples':['Barack Obama','Jennifer Lawrence','Michael Jordan'],
            'relationships':{
            'As_a_lover':'They are warm and supportive partners. They are totally dedicated to their relationship and have a special skill to bring out best in their mate. They are very serious and committed. If somehow their relationship fails, they feel lot of guilt & failure, but they can move on. Best match is with INFP or with ISFP.',
            'As_a_parent':'They take their responsibility seriously and try to be role model to their children. They are supportive, but often they become strict & have high expectations of behaviour from their children. They also try to pass on their belief and values to their children. They do constant efforts to make their children’s environment comforting and cheerful.',
            'As_a_friend':'People with this personality type enjoy helping their friends, and it is important to show that you accept and appreciate what they have to offer. They enjoy supporting and bringing out the best in others. They are energetic and fun to be with. They mix with all sorts of people. ENFJs are not always good at asking for help when they need it.',
            },
            'Career_Opportunities':['Counsellor','Teacher','Psychologist','Social worker','Human resource manager','Sales manager','Author','Designer'],
            },
            
            {
            'idx':14,
            'title':'ENTP',
            'summary':'The Debator (Extraverted, Intuitive, Thinking, Perceiving)',
            'para': 'They are intelligent and knowledgeable. They love discuss facts and theories in extensive detail. ENTPs are logical, rational and objective in their approach to information and arguments. They expect the same from a debating partner. They often described as analysts. They are innovative, clever and idea-oriented. Hence, they often described as “the innovator”, “the visionary” or “the debater”.',
            'characteristics': ['They are visionary. They have ability to see big pictures and also to predict trends. They are more focused on future rather than on the present or the past. Hence, they spend a lot of time in building strategies. ENTPs are capable of generating new ideas and possibly ideas can be so visionary, that they will be useful to the entire world.',
            'They value freedom a lot. They don’t want to be controlled by others and similarly they don’t want to control anyone. Their freedom-loving nature often creates obstacles in their path as they do not want to be confined or to follow strict guidelines. They expect freedom in the way they are doing things.',
            'They have good social skills. They like to be around people. They enjoy to interacting with wide variety of people. They like to engage with great conversations. Their talkative and visionary nature often makes conversation much interesting.',
            'They are very curious. They like to go with new ideas and they are very good at learning new things. They try to understand world around them. They love to gather new ideas and information. Often they quickly come at conclusion. They are quick learner.',
            'ENTPs are good at problem solving. They always try to explore new options, ideas that are innovative. They love to do activities that stimulate their intelligence. They are creative and are good at analysis of complex theories.',
            'Often they seem to be as arrogant ones. Many times they do not want to consider other people’s approval. They judge people based on their reasoning capability. As a result, they can be very direct and honest to the actions of people and they do not take people’s feelings for much consideration.',
            'They can be open, charming and good communicators. They build good relationships with their friends and loved ones. They can be sweet, loving and demonstrative of their emotions.',
            ],
            'strengths':['Fearlessness','Confident','Creative','Knowledgeable','Good social skills','Adaptability','Energetic and charismatic'],
            'weaknesses':['Very argumentative','Intolerant','Dislikes practical matters','Dislikes routines and schedules','Procrastination','Unfocused','Insensitive'],
            'well_known_examples':['Thomas Edison','Leonardo Da Vinci','Alexander The Great'],
            'relationships':{
            'As_a_lover':'They are exciting partners, full of ideas for new things to explore together. They want to know how their partners minds work, and are creative in coming up with solutions to interpersonal problems. They like to encourage their mate to pursue their goals. Their tendency to take risks and over argumentative nature can cause severe problem. Best match is with INFJ or with INTJ personality.',
            'As_a_parent':'They have fun-loving attitude. ENTPs always try to grow their child in the way that they will become independent and logical thinkers. Problem is that they are not consistent. They love to live unrestricted life and this may cause into overlooking to their duties.',
            'As_a_friend':'If we are not going to count on their debating nature, they are very charming, energetic and sweet persons. They love to mix with all sorts of people. They are flexible, easy-going and they enjoy interacting with others. They prefer to be surrounded by people who are intelligent and ideas-oriented. They lack in the ability to sympathize.',
            },
            'Career_Opportunities':['Engineer','Lawyer','Scientist','Psychologist','Researcher','Software developer','Detective','Inventor'],
            },
            
            {
            'idx':15,
            'title':'ENTJ',
            'summary':'The Commander (Extraverted, Intuitive, Thinking, Judging)',
            'para': 'They are assertive, confident and outspoken. ENTJs are the most natural leaders among the 16 personality types. They live in a world of possibilities and see problems & obstacles as their opportunities. They like to take charge of things. They see themselves as a leader or a manager who organize people and processes to achieve their goals. They enjoy developing long-range plans to accomplish their vision.',
            'characteristics': ['They are prone to hide their emotions. Often people see them as insensitive ones. They do like to interact with people, but not to express themselves with them. They keep their emotions as their private sphere of their life and share only in rare case with the close people.',
            'They are logical and thoughtful before taking any action. They make deep deliberations on what will be the consequences of their decision. Often they have proper plans and strategies with them.',
            'ENTJs love challenges. They see challenges as opportunities. They believe they can solve any problem, if they have sufficient resources and time in hand.They care very little about how others see them. They place much importance on getting the job done. They have strong willpower and never give up attitude.They always push themselves towards their goals.',
            'They have growth oriented approach. They always try to grow and improve. Often they tend to become perfectionist. They are self-confident and sure of their abilities.',
            'They like to interact with people. They enjoy spending time with people. They have well-developed communication skills. Being an extrovert, they like be with people and need connections & contact with others.',
            'ENTJs are planners and strategists. Making decisions and having a schedule or course of action planned out gives them a sense of predictability and control.They like to be organized, strategic and discipline. They like to follow schedules and to be prepared for the upcoming tasks.',
            'ENTJs are natural born leaders. They like to take charge of things. Their energetic, active nature and growth oriented approach gives proper direction to the followers. They are good at spotting problems. They place a greater emphasis on objective and logical information. Personal feeling and emotions of others tend not to factor much into their choices.',
            ],
            'strengths':['Strong leadership skills','Self-assured','Well-organized','Self-confident and strategic thinkers','Good at making decisions','Assertive and outspoken','Strong communication skills'],
            'weaknesses':['Impatient','Arrogant','Stubborn','Insensitive','Aggressive','Intolerant'],
            'well_known_examples':['Mustafa Kemal Ataturk','Napoleon Bonaparte','Franklin D. Roosevelt'],
            'relationships':{
            'As_a_lover':'They have high expectations from themselves and from their parent to make their life more successful. They seek for growth or constant improvement. They may lack in understanding their partners’ feelings or emotions. They take responsibility and accountability & expect to be in charge. Best partners is with INTP or with ISTP personality.',
            'As_a_parent':'They take parenting as a serious responsibility. They make sure that their child is constantly developing and learning in most optimal way. They are strict and they have high expectations from their children. They continuously promote independent learning and thinking. They expect their children will follow their lead.',
            'As_a_friend':'They love to involve in quality conversations with people who share similar view or who can teach them something new. ENTJs prefer to make stimulating, dynamic and interesting friends. AS they have much less patience, they tend to avoid people who are very different on life and perspectives.',
            },
            'Career_Opportunities':['Entrepreneur','Lawyer','Scientist','Human Resource Manager','Software Developer','Company CEO or manager','Business Analyst','Public Speaker'],
            }
]